/// Lista estática de países do mundo, usada pelo seletor de país de
/// origem no cadastro/edição de vinhos.
///
/// Cada item é um mapa com as chaves:
/// - `nome`: nome do país em português;
/// - `bandeira`: emoji da bandeira correspondente.
///
/// A lista inclui os principais países produtores de vinho e mais comuns
/// no contexto brasileiro, além de todos os demais países do mundo.
final List<Map<String, String>> paisesDoMundo = [
  {'nome': 'Afeganistão', 'bandeira': '🇦🇫'},
  {'nome': 'África do Sul', 'bandeira': '🇿🇦'},
  {'nome': 'Albânia', 'bandeira': '🇦🇱'},
  {'nome': 'Alemanha', 'bandeira': '🇩🇪'},
  {'nome': 'Andorra', 'bandeira': '🇦🇩'},
  {'nome': 'Angola', 'bandeira': '🇦🇴'},
  {'nome': 'Antígua e Barbuda', 'bandeira': '🇦🇬'},
  {'nome': 'Arábia Saudita', 'bandeira': '🇸🇦'},
  {'nome': 'Argélia', 'bandeira': '🇩🇿'},
  {'nome': 'Argentina', 'bandeira': '🇦🇷'},
  {'nome': 'Armênia', 'bandeira': '🇦🇲'},
  {'nome': 'Austrália', 'bandeira': '🇦🇺'},
  {'nome': 'Áustria', 'bandeira': '🇦🇹'},
  {'nome': 'Azerbaijão', 'bandeira': '🇦🇿'},
  {'nome': 'Bahamas', 'bandeira': '🇧🇸'},
  {'nome': 'Bahrein', 'bandeira': '🇧🇭'},
  {'nome': 'Bangladesh', 'bandeira': '🇧🇩'},
  {'nome': 'Barbados', 'bandeira': '🇧🇧'},
  {'nome': 'Bélgica', 'bandeira': '🇧🇪'},
  {'nome': 'Belize', 'bandeira': '🇧🇿'},
  {'nome': 'Benin', 'bandeira': '🇧🇯'},
  {'nome': 'Bielorrússia', 'bandeira': '🇧🇾'},
  {'nome': 'Bolívia', 'bandeira': '🇧🇴'},
  {'nome': 'Bósnia e Herzegovina', 'bandeira': '🇧🇦'},
  {'nome': 'Botsuana', 'bandeira': '🇧🇼'},
  {'nome': 'Brasil', 'bandeira': '🇧🇷'},
  {'nome': 'Brunei', 'bandeira': '🇧🇳'},
  {'nome': 'Bulgária', 'bandeira': '🇧🇬'},
  {'nome': 'Burquina Faso', 'bandeira': '🇧🇫'},
  {'nome': 'Burundi', 'bandeira': '🇧🇮'},
  {'nome': 'Butão', 'bandeira': '🇧🇹'},
  {'nome': 'Cabo Verde', 'bandeira': '🇨🇻'},
  {'nome': 'Camarões', 'bandeira': '🇨🇲'},
  {'nome': 'Camboja', 'bandeira': '🇰🇭'},
  {'nome': 'Canadá', 'bandeira': '🇨🇦'},
  {'nome': 'Catar', 'bandeira': '🇶🇦'},
  {'nome': 'Cazaquistão', 'bandeira': '🇰🇿'},
  {'nome': 'Chade', 'bandeira': '🇹🇩'},
  {'nome': 'Chile', 'bandeira': '🇨🇱'},
  {'nome': 'China', 'bandeira': '🇨🇳'},
  {'nome': 'Chipre', 'bandeira': '🇨🇾'},
  {'nome': 'Colômbia', 'bandeira': '🇨🇴'},
  {'nome': 'Comores', 'bandeira': '🇰🇲'},
  {'nome': 'Congo', 'bandeira': '🇨🇬'},
  {'nome': 'Coreia do Norte', 'bandeira': '🇰🇵'},
  {'nome': 'Coreia do Sul', 'bandeira': '🇰🇷'},
  {'nome': 'Costa do Marfim', 'bandeira': '🇨🇮'},
  {'nome': 'Costa Rica', 'bandeira': '🇨🇷'},
  {'nome': 'Croácia', 'bandeira': '🇭🇷'},
  {'nome': 'Cuba', 'bandeira': '🇨🇺'},
  {'nome': 'Dinamarca', 'bandeira': '🇩🇰'},
  {'nome': 'Djibuti', 'bandeira': '🇩🇯'},
  {'nome': 'Dominica', 'bandeira': '🇩🇲'},
  {'nome': 'Egito', 'bandeira': '🇪🇬'},
  {'nome': 'El Salvador', 'bandeira': '🇸🇻'},
  {'nome': 'Emirados Árabes Unidos', 'bandeira': '🇦🇪'},
  {'nome': 'Equador', 'bandeira': '🇪🇨'},
  {'nome': 'Eritreia', 'bandeira': '🇪🇷'},
  {'nome': 'Eslováquia', 'bandeira': '🇸🇰'},
  {'nome': 'Eslovênia', 'bandeira': '🇸🇮'},
  {'nome': 'Espanha', 'bandeira': '🇪🇸'},
  {'nome': 'Essuatíni', 'bandeira': '🇸🇿'},
  {'nome': 'Estados Unidos', 'bandeira': '🇺🇸'},
  {'nome': 'Estônia', 'bandeira': '🇪🇪'},
  {'nome': 'Etiópia', 'bandeira': '🇪🇹'},
  {'nome': 'Fiji', 'bandeira': '🇫🇯'},
  {'nome': 'Filipinas', 'bandeira': '🇵🇭'},
  {'nome': 'Finlândia', 'bandeira': '🇫🇮'},
  {'nome': 'França', 'bandeira': '🇫🇷'},
  {'nome': 'Gabão', 'bandeira': '🇬🇦'},
  {'nome': 'Gâmbia', 'bandeira': '🇬🇲'},
  {'nome': 'Gana', 'bandeira': '🇬🇭'},
  {'nome': 'Geórgia', 'bandeira': '🇬🇪'},
  {'nome': 'Granada', 'bandeira': '🇬🇩'},
  {'nome': 'Grécia', 'bandeira': '🇬🇷'},
  {'nome': 'Guatemala', 'bandeira': '🇬🇹'},
  {'nome': 'Guiana', 'bandeira': '🇬🇾'},
  {'nome': 'Guiné', 'bandeira': '🇬🇳'},
  {'nome': 'Guiné-Bissau', 'bandeira': '🇬🇼'},
  {'nome': 'Guiné Equatorial', 'bandeira': '🇬🇶'},
  {'nome': 'Haiti', 'bandeira': '🇭🇹'},
  {'nome': 'Honduras', 'bandeira': '🇭🇳'},
  {'nome': 'Hungria', 'bandeira': '🇭🇺'},
  {'nome': 'Iêmen', 'bandeira': '🇾🇪'},
  {'nome': 'Ilhas Marshall', 'bandeira': '🇲🇭'},
  {'nome': 'Ilhas Salomão', 'bandeira': '🇸🇧'},
  {'nome': 'Índia', 'bandeira': '🇮🇳'},
  {'nome': 'Indonésia', 'bandeira': '🇮🇩'},
  {'nome': 'Irã', 'bandeira': '🇮🇷'},
  {'nome': 'Iraque', 'bandeira': '🇮🇶'},
  {'nome': 'Irlanda', 'bandeira': '🇮🇪'},
  {'nome': 'Islândia', 'bandeira': '🇮🇸'},
  {'nome': 'Israel', 'bandeira': '🇮🇱'},
  {'nome': 'Itália', 'bandeira': '🇮🇹'},
  {'nome': 'Jamaica', 'bandeira': '🇯🇲'},
  {'nome': 'Japão', 'bandeira': '🇯🇵'},
  {'nome': 'Jordânia', 'bandeira': '🇯🇴'},
  {'nome': 'Kiribati', 'bandeira': '🇰🇮'},
  {'nome': 'Kuwait', 'bandeira': '🇰🇼'},
  {'nome': 'Laos', 'bandeira': '🇱🇦'},
  {'nome': 'Lesoto', 'bandeira': '🇱🇸'},
  {'nome': 'Letônia', 'bandeira': '🇱🇻'},
  {'nome': 'Líbano', 'bandeira': '🇱🇧'},
  {'nome': 'Libéria', 'bandeira': '🇱🇷'},
  {'nome': 'Líbia', 'bandeira': '🇱🇾'},
  {'nome': 'Liechtenstein', 'bandeira': '🇱🇮'},
  {'nome': 'Lituânia', 'bandeira': '🇱🇹'},
  {'nome': 'Luxemburgo', 'bandeira': '🇱🇺'},
  {'nome': 'Macedônia do Norte', 'bandeira': '🇲🇰'},
  {'nome': 'Madagascar', 'bandeira': '🇲🇬'},
  {'nome': 'Malásia', 'bandeira': '🇲🇾'},
  {'nome': 'Malawi', 'bandeira': '🇲🇼'},
  {'nome': 'Maldivas', 'bandeira': '🇲🇻'},
  {'nome': 'Mali', 'bandeira': '🇲🇱'},
  {'nome': 'Malta', 'bandeira': '🇲🇹'},
  {'nome': 'Marrocos', 'bandeira': '🇲🇦'},
  {'nome': 'Maurícia', 'bandeira': '🇲🇺'},
  {'nome': 'Mauritânia', 'bandeira': '🇲🇷'},
  {'nome': 'México', 'bandeira': '🇲🇽'},
  {'nome': 'Mianmar', 'bandeira': '🇲🇲'},
  {'nome': 'Micronésia', 'bandeira': '🇫🇲'},
  {'nome': 'Moçambique', 'bandeira': '🇲🇿'},
  {'nome': 'Moldávia', 'bandeira': '🇲🇩'},
  {'nome': 'Mônaco', 'bandeira': '🇲🇨'},
  {'nome': 'Mongólia', 'bandeira': '🇲🇳'},
  {'nome': 'Montenegro', 'bandeira': '🇲🇪'},
  {'nome': 'Namíbia', 'bandeira': '🇳🇦'},
  {'nome': 'Nauru', 'bandeira': '🇳🇷'},
  {'nome': 'Nepal', 'bandeira': '🇳🇵'},
  {'nome': 'Nicarágua', 'bandeira': '🇳🇮'},
  {'nome': 'Níger', 'bandeira': '🇳🇪'},
  {'nome': 'Nigéria', 'bandeira': '🇳🇬'},
  {'nome': 'Noruega', 'bandeira': '🇳🇴'},
  {'nome': 'Nova Zelândia', 'bandeira': '🇳🇿'},
  {'nome': 'Omã', 'bandeira': '🇴🇲'},
  {'nome': 'Países Baixos', 'bandeira': '🇳🇱'},
  {'nome': 'Palau', 'bandeira': '🇵🇼'},
  {'nome': 'Panamá', 'bandeira': '🇵🇦'},
  {'nome': 'Papua-Nova Guiné', 'bandeira': '🇵🇬'},
  {'nome': 'Paquistão', 'bandeira': '🇵🇰'},
  {'nome': 'Paraguai', 'bandeira': '🇵🇾'},
  {'nome': 'Peru', 'bandeira': '🇵🇪'},
  {'nome': 'Polônia', 'bandeira': '🇵🇱'},
  {'nome': 'Portugal', 'bandeira': '🇵🇹'},
  {'nome': 'Quênia', 'bandeira': '🇰🇪'},
  {'nome': 'Quirguistão', 'bandeira': '🇰🇬'},
  {'nome': 'Reino Unido', 'bandeira': '🇬🇧'},
  {'nome': 'República Centro-Africana', 'bandeira': '🇨🇫'},
  {'nome': 'República Democrática do Congo', 'bandeira': '🇨🇩'},
  {'nome': 'República Dominicana', 'bandeira': '🇩🇴'},
  {'nome': 'República Tcheca', 'bandeira': '🇨🇿'},
  {'nome': 'Romênia', 'bandeira': '🇷🇴'},
  {'nome': 'Ruanda', 'bandeira': '🇷🇼'},
  {'nome': 'Rússia', 'bandeira': '🇷🇺'},
  {'nome': 'Samoa', 'bandeira': '🇼🇸'},
  {'nome': 'San Marino', 'bandeira': '🇸🇲'},
  {'nome': 'Santa Lúcia', 'bandeira': '🇱🇨'},
  {'nome': 'São Cristóvão e Névis', 'bandeira': '🇰🇳'},
  {'nome': 'São Tomé e Príncipe', 'bandeira': '🇸🇹'},
  {'nome': 'São Vicente e Granadinas', 'bandeira': '🇻🇨'},
  {'nome': 'Senegal', 'bandeira': '🇸🇳'},
  {'nome': 'Serra Leoa', 'bandeira': '🇸🇱'},
  {'nome': 'Sérvia', 'bandeira': '🇷🇸'},
  {'nome': 'Seicheles', 'bandeira': '🇸🇨'},
  {'nome': 'Singapura', 'bandeira': '🇸🇬'},
  {'nome': 'Síria', 'bandeira': '🇸🇾'},
  {'nome': 'Somália', 'bandeira': '🇸🇴'},
  {'nome': 'Sri Lanka', 'bandeira': '🇱🇰'},
  {'nome': 'Sudão', 'bandeira': '🇸🇩'},
  {'nome': 'Sudão do Sul', 'bandeira': '🇸🇸'},
  {'nome': 'Suécia', 'bandeira': '🇸🇪'},
  {'nome': 'Suíça', 'bandeira': '🇨🇭'},
  {'nome': 'Suriname', 'bandeira': '🇸🇷'},
  {'nome': 'Tailândia', 'bandeira': '🇹🇭'},
  {'nome': 'Tanzânia', 'bandeira': '🇹🇿'},
  {'nome': 'Tajiquistão', 'bandeira': '🇹🇯'},
  {'nome': 'Timor-Leste', 'bandeira': '🇹🇱'},
  {'nome': 'Togo', 'bandeira': '🇹🇬'},
  {'nome': 'Tonga', 'bandeira': '🇹🇴'},
  {'nome': 'Trinidad e Tobago', 'bandeira': '🇹🇹'},
  {'nome': 'Tunísia', 'bandeira': '🇹🇳'},
  {'nome': 'Turcomenistão', 'bandeira': '🇹🇲'},
  {'nome': 'Turquia', 'bandeira': '🇹🇷'},
  {'nome': 'Tuvalu', 'bandeira': '🇹🇻'},
  {'nome': 'Ucrânia', 'bandeira': '🇺🇦'},
  {'nome': 'Uganda', 'bandeira': '🇺🇬'},
  {'nome': 'Uruguai', 'bandeira': '🇺🇾'},
  {'nome': 'Uzbequistão', 'bandeira': '🇺🇿'},
  {'nome': 'Vanuatu', 'bandeira': '🇻🇺'},
  {'nome': 'Vaticano', 'bandeira': '🇻🇦'},
  {'nome': 'Venezuela', 'bandeira': '🇻🇪'},
  {'nome': 'Vietnã', 'bandeira': '🇻🇳'},
  {'nome': 'Zâmbia', 'bandeira': '🇿🇲'},
  {'nome': 'Zimbábue', 'bandeira': '🇿🇼'},
];
